/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bll.Manager;
import dao.CarDAO;
import dao.CarModelDAO;
import dao.ServiceDAO;
import dao.ServiceDetailsDAO;
import dto.Car;
import dto.CarModel;
import dto.Service;
import dto.ServiceDetails;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.text.JTextComponent;

/**
 *
 * 
 */
public class frmCar extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form frmCar
     */
    public frmCar() {
        initComponents();
        new Utility().setIcon("/resources/car_icon-150x150.gif", this, null);
        setLang(Main.baseName);
        loadListService();
        setComboModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JPanel4 = new javax.swing.JPanel();
        lblCarInfor = new javax.swing.JLabel();
        lblModelName = new javax.swing.JLabel();
        lblServiceName = new javax.swing.JLabel();
        pnlAddInfor = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaAddInfor = new javax.swing.JTextArea();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnAccept = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        cbxModel = new javax.swing.JComboBox();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lServiceName = new javax.swing.JScrollPane();
        jListServiceName = new javax.swing.JList();
        lblStatus = new javax.swing.JLabel();
        lblAvailable = new javax.swing.JCheckBox();
        lblCarno = new javax.swing.JLabel();
        lblCarNo = new javax.swing.JLabel();
        pnlImage = new javax.swing.JPanel();
        lblPhoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Car");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        JPanel4.setBackground(new java.awt.Color(255, 255, 255));
        JPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(192, 192, 192)));
        JPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCarInfor.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        lblCarInfor.setForeground(new java.awt.Color(0, 51, 255));
        lblCarInfor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCarInfor.setText("CAR INFORMATION");
        JPanel4.add(lblCarInfor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 12, 685, 60));

        lblModelName.setText("Model");
        JPanel4.add(lblModelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 156, 48, -1));

        lblServiceName.setText("Service Name");
        JPanel4.add(lblServiceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 96, 79, -1));

        pnlAddInfor.setBackground(new java.awt.Color(255, 255, 255));
        pnlAddInfor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Additional Information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jScrollPane1.setBorder(null);
        jScrollPane1.setToolTipText("");

        txaAddInfor.setColumns(20);
        txaAddInfor.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txaAddInfor.setRows(5);
        jScrollPane1.setViewportView(txaAddInfor);

        javax.swing.GroupLayout pnlAddInforLayout = new javax.swing.GroupLayout(pnlAddInfor);
        pnlAddInfor.setLayout(pnlAddInforLayout);
        pnlAddInforLayout.setHorizontalGroup(
            pnlAddInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(pnlAddInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
        );
        pnlAddInforLayout.setVerticalGroup(
            pnlAddInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
            .addGroup(pnlAddInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAddInforLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))
        );

        JPanel4.add(pnlAddInfor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 610, -1));

        lblPrice.setText("Price");
        JPanel4.add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 256, 48, -1));
        JPanel4.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 253, 139, -1));

        jLabel10.setText("($)");
        JPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 256, 22, -1));

        btnAccept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/OK-20.gif"))); // NOI18N
        btnAccept.setText("Accept");
        btnAccept.setActionCommand("add");
        btnAccept.addActionListener(this);
        JPanel4.add(btnAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, -1, -1));

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancel.gif"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setActionCommand("cancel");
        btnCancel.addActionListener(this);
        JPanel4.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, -1, -1));

        cbxModel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxModel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxModelItemStateChanged(evt);
            }
        });
        JPanel4.add(cbxModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 153, 170, -1));

        lblName.setText("Name");
        JPanel4.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 207, 48, -1));
        JPanel4.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 204, 170, -1));

        jListServiceName.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListServiceName.setFixedCellHeight(24);
        jListServiceName.setVisibleRowCount(5);
        lServiceName.setViewportView(jListServiceName);

        JPanel4.add(lServiceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 96, 213, 77));

        lblStatus.setText("Status");
        JPanel4.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 296, 48, -1));

        lblAvailable.setBackground(new java.awt.Color(255, 255, 255));
        lblAvailable.setSelected(true);
        lblAvailable.setText("Available");
        JPanel4.add(lblAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 292, -1, -1));

        lblCarno.setText("Car No");
        JPanel4.add(lblCarno, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 104, 63, -1));
        JPanel4.add(lblCarNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 104, 160, -1));

        pnlImage.setBackground(new java.awt.Color(255, 255, 255));
        pnlImage.setBorder(javax.swing.BorderFactory.createTitledBorder("Image"));
        pnlImage.setAutoscrolls(true);
        pnlImage.setLayout(new java.awt.BorderLayout());

        lblPhoto.setBackground(new java.awt.Color(255, 255, 255));
        lblPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlImage.add(lblPhoto, java.awt.BorderLayout.CENTER);

        JPanel4.add(pnlImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 191, 296, 172));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(733, 673));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxModelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxModelItemStateChanged
        // TODO add your handling code here:
        lblPhoto.setIcon(new ImageIcon(new CarModelDAO().getCarModel(cbxModel.getSelectedItem()+"").getImage()));
    }//GEN-LAST:event_cbxModelItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel4;
    public javax.swing.JButton btnAccept;
    public javax.swing.JButton btnCancel;
    public javax.swing.JComboBox cbxModel;
    private javax.swing.JLabel jLabel10;
    public javax.swing.JList jListServiceName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane lServiceName;
    public javax.swing.JCheckBox lblAvailable;
    public javax.swing.JLabel lblCarInfor;
    public javax.swing.JLabel lblCarNo;
    public javax.swing.JLabel lblCarno;
    public javax.swing.JLabel lblModelName;
    public javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoto;
    public javax.swing.JLabel lblPrice;
    public javax.swing.JLabel lblServiceName;
    public javax.swing.JLabel lblStatus;
    public javax.swing.JPanel pnlAddInfor;
    public javax.swing.JPanel pnlImage;
    public javax.swing.JTextArea txaAddInfor;
    public javax.swing.JTextField txtName;
    public javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables

    public void setLang(String baseName){
        Locale locale = Locale.getDefault();
        ResourceBundle rb = ResourceBundle.getBundle(baseName, locale);
        lblCarno.setText(rb.getString("carNo"));
        lblModelName.setText(rb.getString("modelName"));
        lblPrice.setText(rb.getString("price"));
        lblStatus.setText(rb.getString("status"));
        lblServiceName.setText(rb.getString("serviceName"));
        pnlAddInfor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, rb.getString("addInfor"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        pnlImage.setBorder(javax.swing.BorderFactory.createTitledBorder(rb.getString("image")));
        btnAccept.setText(rb.getString("accept"));
        btnCancel.setText(rb.getString("cancel"));
        lblCarInfor.setText(rb.getString("carInformation"));
        lblAvailable.setText(rb.getString("available"));
    }
    public void loadEmptyForm() {
        lblCarNo.setText(new Manager().getNewID("Car") + "");
        cbxModel.setSelectedIndex(0);
        txtName.setText("");
        txtName.setBackground(new Color(255, 255, 255));
        txtPrice.setText("");
        txtPrice.setBackground(new Color(255, 255, 255));
        lblAvailable.setSelected(true);
        jListServiceName.setSelectedIndex(0);
        txaAddInfor.setText("");
        txaAddInfor.setBackground(new Color(255, 255, 255));
        lblPhoto.setIcon(new ImageIcon(new CarModelDAO().getCarModel(cbxModel.getSelectedItem()+"").getImage()));
    }

    public void loadListService() {
        Vector v = new Vector();
        ArrayList list = new Manager().getList("service");
        for (int i = 0; i < list.size(); i++) {
            Service s = (Service) list.get(i);
            v.add(s.getName());
        }
        jListServiceName.setListData(v);
    }

    public void setComboModel() {
        ArrayList list = new Manager().getList("model");
        Vector data = new Vector();
        for (int i = 0; i < list.size(); i++) {
            CarModel cm = (CarModel) list.get(i);
            data.add(cm.getModelName());
        }
        DefaultComboBoxModel model = new DefaultComboBoxModel(data);
        cbxModel.setModel(model);
    }

    public void loadCarData(long CarNo) {
        Car c = new CarDAO().getCar(CarNo);
        lblCarNo.setText(c.getCarNo() + "");
        cbxModel.setSelectedItem(c.getModelName());
        txtName.setText(c.getName());
        txtPrice.setText(c.getPrice() + "");
        txaAddInfor.setText(c.getAddInfor());
        lblAvailable.setSelected(c.isStatus());
        String[] arrName = new ServiceDetailsDAO().getServiceName(CarNo);
        ArrayList list = new ArrayList();
        for (int i = 0; i < jListServiceName.getModel().getSize(); i++) {
            for (int j = 0; j < arrName.length; j++) {
                if (arrName[j].equals(jListServiceName.getModel().getElementAt(i))) {
                    list.add(i);
                }
            }
        }
        int[] indicates = new int[list.size()];
        for (int i = 0; i < list.size(); i++) {
            indicates[i] = (int) list.get(i);
        }
        jListServiceName.setSelectedIndices(indicates);
        lblPhoto.setIcon(new ImageIcon(new CarModelDAO().getCarModel(c.getModelName()).getImage()));
    }
    public void addServiceDetails(ArrayList list, long CarNo){
        for (int i = 0; i < list.size(); i++) {
                ServiceDetails sd = new ServiceDetails(new ServiceDAO().getID(list.get(i) + ""), CarNo);
                new Manager().addNew(sd, "serviceDetails");
            }
    }
    public Car getValue() {
        Car car = new Car();
        car.setName(txtName.getText());
        car.setPrice(Float.parseFloat(txtPrice.getText()));
        car.setStatus(lblAvailable.isSelected());
        car.setModelName(cbxModel.getSelectedItem() + "");
        ArrayList list = (ArrayList) jListServiceName.getSelectedValuesList();
        if (list.size() == 0) {
            Message.error("Please select service name!");
            return null;
        }
        if (btnAccept.getActionCommand().equals("update")) {
            new Manager().delete(pnlCar.CarNo, "serviceDetails");

            for (int i = 0; i < list.size(); i++) {
                ServiceDetails sd = new ServiceDetails(new ServiceDAO().getID(list.get(i) + ""), pnlCar.CarNo);
                car.setCarNo(pnlCar.CarNo);
                new Manager().addNew(sd, "serviceDetails");
            }
        }
        car.setAddInfor(txaAddInfor.getText());
        return car;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        JTextComponent[] tcp = {txtName};
        JTextComponent[] tcpNumber = {txtPrice};
        switch (e.getActionCommand()) {
            case "add":
                if (!Validator.validateComponents(tcp) || !Validator.validateNumber(tcpNumber)) {
                    return;
                }
                Car car = getValue();
                car.setCarNo(Long.parseLong(lblCarNo.getText()));
                new Manager().addNew(car, "car");
                ArrayList list = (ArrayList) jListServiceName.getSelectedValuesList();
                addServiceDetails(list, car.getCarNo());
                this.dispose();
                break;
            case "update":
                if (!Validator.validateComponents(tcp) || !Validator.validateNumber(tcpNumber)) {
                    return;
                }
                new Manager().update(getValue(), "car");
                this.dispose();
                break;
            case "cancel":
                this.dispose();
                break;

        }
    }
}
