/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bll.Manager;
import dao.CarModelDAO;
import dao.ManufactoryDAO;
import dto.CarModel;
import dto.Manufactory;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.text.JTextComponent;

/**
 *
 * 
 */
public class frmCarModel extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form frmCarModel
     */
    public frmCarModel() {
        initComponents();
        new Utility().setIcon("/resources/carModel.gif", this, null);
        setLang(Main.baseName);
        setComboModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        pnlModelInfor = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        pnlImage = new javax.swing.JPanel();
        lblPhoto = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        lblAddInfor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaAddInfor = new javax.swing.JTextArea();
        btnAccept = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblManufactory = new javax.swing.JLabel();
        cbxManufactory = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update Car Model Information");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlModelInfor.setBackground(new java.awt.Color(255, 255, 255));
        pnlModelInfor.setBorder(javax.swing.BorderFactory.createTitledBorder("Car's Model Information"));
        pnlModelInfor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setText("Name");
        pnlModelInfor.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 97, 45, -1));
        pnlModelInfor.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 94, 150, -1));

        pnlImage.setBackground(new java.awt.Color(255, 255, 255));
        pnlImage.setBorder(javax.swing.BorderFactory.createTitledBorder("Image"));
        pnlImage.setAutoscrolls(true);
        pnlImage.setLayout(new java.awt.BorderLayout());

        lblPhoto.setBackground(new java.awt.Color(255, 255, 255));
        lblPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlImage.add(lblPhoto, java.awt.BorderLayout.CENTER);

        pnlModelInfor.add(pnlImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 60, 230, 172));

        btnBrowse.setText("Browse");
        btnBrowse.setActionCommand("browse");
        btnBrowse.addActionListener(this);
        pnlModelInfor.add(btnBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 238, -1, -1));

        lblAddInfor.setText("Add Informations");
        pnlModelInfor.add(lblAddInfor, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 132, -1, -1));

        txaAddInfor.setColumns(20);
        txaAddInfor.setRows(5);
        jScrollPane1.setViewportView(txaAddInfor);

        pnlModelInfor.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 157, 290, 121));

        btnAccept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/OK-20.gif"))); // NOI18N
        btnAccept.setActionCommand("add");
        btnAccept.setText("Accept");
        btnAccept.addActionListener(this);
        pnlModelInfor.add(btnAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancel.gif"))); // NOI18N
        btnCancel.setActionCommand("cancel");
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this);
        pnlModelInfor.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));

        lblManufactory.setText("Manufactory");
        pnlModelInfor.add(lblManufactory, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 59, -1, -1));

        cbxManufactory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlModelInfor.add(cbxManufactory, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 56, 150, -1));

        jPanel3.add(pnlModelInfor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 9, 620, 360));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 380));

        setSize(new java.awt.Dimension(653, 415));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCarModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCarModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCarModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCarModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCarModel().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAccept;
    public javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnCancel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbxManufactory;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddInfor;
    private javax.swing.JLabel lblManufactory;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JPanel pnlImage;
    private javax.swing.JPanel pnlModelInfor;
    private javax.swing.JTextArea txaAddInfor;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
    private static String path = "";
    private static byte[] tempImage = null;
    public static String ManufactoryName;

    public void setLang(String baseName) {
        Locale locale = Locale.getDefault();
        ResourceBundle rb = ResourceBundle.getBundle(baseName, locale);
        pnlModelInfor.setBorder(javax.swing.BorderFactory.createTitledBorder(rb.getString("carModelInfor")));
        lblManufactory.setText(rb.getString("manufactory"));
        btnBrowse.setText(rb.getString("browse"));
        btnAccept.setText(rb.getString("accept"));
        btnCancel.setText(rb.getString("cancel"));
        lblName.setText(rb.getString("name"));
        lblAddInfor.setText(rb.getString("addInfor"));
        pnlImage.setBorder(javax.swing.BorderFactory.createTitledBorder(rb.getString("image")));
    }

    public void loadData(String Name) {
        path = "";
        CarModel cm = new CarModelDAO().getCarModel(Name);
        tempImage = cm.getImage();
        cbxManufactory.setSelectedItem(ManufactoryName);
        txtName.setText(cm.getModelName());
        txaAddInfor.setText(cm.getAddInfor());
        lblPhoto.setIcon(new ImageIcon(cm.getImage()));
    }

    public void setComboModel() {
        ArrayList list = new Manager().getList("manufactory");
        Vector data = new Vector();
        for (int i = 0; i < list.size(); i++) {
            Manufactory mf = (Manufactory) list.get(i);
            data.add(mf.getName());
        }
        DefaultComboBoxModel model = new DefaultComboBoxModel(data);
        cbxManufactory.setModel(model);
    }

    public CarModel getValue() {
        CarModel cm = new CarModel();
        cm.setModelName(txtName.getText());
        cm.setAddInfor(txaAddInfor.getText());
        cm.setManufactoryID(new ManufactoryDAO().getID(cbxManufactory.getSelectedItem().toString()));
        boolean status = false;
        if (!path.equals("")) {
            try {
                File f = new File(path);
                FileInputStream in = new FileInputStream(f);
                byte[] photo = new byte[(int) f.length()];
                in.read(photo);
                cm.setImage(photo);
            } catch (FileNotFoundException ex) {
                Message.error("Can't find file images!\nPlease try again.");
                return null;
            } catch (IOException ex) {
                Message.error("Can't read the file!\nPlease try again.");
                return null;
            }
        } else if (tempImage != null) {
            cm.setImage(tempImage);
        }
        return cm;
    }

    public void clearForm() {
        cbxManufactory.setSelectedIndex(0);
        txtName.setText("");
        txtName.setBackground(new Color(255, 255, 255));
        txaAddInfor.setText("");
        txaAddInfor.setBackground(new Color(255, 255, 255));
        lblPhoto.setIcon(null);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        JTextComponent[] tcp = {txtName};
        switch (e.getActionCommand()) {
            case "add":
                if (!Validator.validateComponents(tcp) || !Validator.validateImage(lblPhoto)) {
                    return;
                }
                new Manager().addNew(getValue(), "model");
                this.dispose();
                break;
            case "update":
                if (!Validator.validateComponents(tcp) || !Validator.validateImage(lblPhoto)) {
                    return;
                }
                new Manager().update(getValue(), "model");
                this.dispose();
                break;
            case "cancel":
                this.dispose();
                break;
            case "browse":
                path = SelectFile.selectImages();
                if (!path.equals("")) {
                    lblPhoto.setIcon(new ImageIcon(path));
                }
                break;
        }
    }
}
