/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bll.Manager;
import dao.CarReceiptDAO;
import dao.EmployeeDAO;
import dto.CarReceipt;
import dto.Employee;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Date;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * 
 */
public class frmReceipt extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form frmReceipt
     */
    public frmReceipt() {
        initComponents();
        new Utility().setIcon("/resources/receiptGif.gif", this, null);
        setLang(Main.baseName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnlReceipt = new javax.swing.JPanel();
        lblReceipt = new javax.swing.JLabel();
        lblPurchaseID = new javax.swing.JLabel();
        lblPurchaseOrderID = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        dpkDate = new org.jdesktop.swingx.JXDatePicker();
        lblEmpName = new javax.swing.JLabel();
        btnAccept = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblEmployeeName = new javax.swing.JLabel();
        lblReceiptID = new javax.swing.JLabel();
        btnPurchase = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Get Receipt Information");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        pnlReceipt.setBackground(new java.awt.Color(255, 255, 255));
        pnlReceipt.setBorder(javax.swing.BorderFactory.createTitledBorder("Receipt Information"));
        pnlReceipt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblReceipt.setText("Receipt ID");
        pnlReceipt.add(lblReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 78, -1, -1));

        lblPurchaseID.setText("Purchase Order ID");
        pnlReceipt.add(lblPurchaseID, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 46, -1, -1));
        pnlReceipt.add(lblPurchaseOrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 46, -1, -1));

        lblDate.setText("Date");
        pnlReceipt.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 114, -1, -1));

        dpkDate.setFormats("dd/MM/yyyy");
        Calendar cld = Calendar.getInstance();
        dpkDate.setDate(cld.getTime());
        pnlReceipt.add(dpkDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 110, 150, -1));

        lblEmpName.setText("Employee Name");
        pnlReceipt.add(lblEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 150, -1, -1));

        btnAccept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/OK-20.gif"))); // NOI18N
        btnAccept.setText("Accept");
        btnAccept.setActionCommand("add");
        btnAccept.addActionListener(this);
        pnlReceipt.add(btnAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 202, 120, -1));

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancel.gif"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setActionCommand("cancel");
        btnCancel.addActionListener(this);
        pnlReceipt.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 202, 120, -1));

        lblEmployeeName.setText("jLabel5");
        pnlReceipt.add(lblEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 150, -1, -1));

        lblReceiptID.setText("Auto Increment");
        pnlReceipt.add(lblReceiptID, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 78, -1, -1));

        btnPurchase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/order-17x20.gif"))); // NOI18N
        btnPurchase.setText("Purchase");
        btnPurchase.setActionCommand("purchase");
        btnPurchase.addActionListener(this);
        pnlReceipt.add(btnPurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 202, 130, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-489)/2, (screenSize.height-356)/2, 489, 356);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReceipt().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAccept;
    public javax.swing.JButton btnCancel;
    public javax.swing.JButton btnPurchase;
    private org.jdesktop.swingx.JXDatePicker dpkDate;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDate;
    public javax.swing.JLabel lblEmpName;
    public javax.swing.JLabel lblEmployeeName;
    private javax.swing.JLabel lblPurchaseID;
    public static javax.swing.JLabel lblPurchaseOrderID;
    private javax.swing.JLabel lblReceipt;
    public javax.swing.JLabel lblReceiptID;
    private javax.swing.JPanel pnlReceipt;
    // End of variables declaration//GEN-END:variables
    public static long ID;

    public void setLang(String baseName) {
        Locale locale = Locale.getDefault();
        ResourceBundle rb = ResourceBundle.getBundle(baseName, locale);
        pnlReceipt.setBorder(javax.swing.BorderFactory.createTitledBorder(rb.getString("receiptInfor")));
        lblReceipt.setText(rb.getString("receiptID"));
        lblEmpName.setText(rb.getString("empName"));
        lblDate.setText(rb.getString("date"));
        lblPurchaseID.setText(rb.getString("purchaseID"));
        btnPurchase.setText(rb.getString("purchase"));
        btnAccept.setText(rb.getString("accept"));
        btnCancel.setText(rb.getString("cancel"));
    }

    public void loadReceiptData(long ReceiptID) {
        CarReceipt cr = new CarReceiptDAO().getCarReceiptByID(ReceiptID);
        lblReceiptID.setText(cr.getReceiptID() + "");
        lblPurchaseOrderID.setText(cr.getPurchaseOrderID() + "");
        Employee emp = new EmployeeDAO().getEmployee(cr.getEmployeeID());
        String name = emp.getFirstName() + "" + emp.getLastName();
        lblEmployeeName.setName(name);
        dpkDate.setDate(cr.getDate());
    }

    public CarReceipt getValue() {
        CarReceipt r = new CarReceipt();
        r.setPurchaseOrderID(Long.parseLong(lblPurchaseOrderID.getText()));
        if (!lblReceiptID.getText().equals("Auto Increment")) {
            r.setReceiptID(Long.parseLong(lblReceiptID.getText()));
        } else {
            r.setReceiptID(0);
        }
        r.setDate(new Date(dpkDate.getDate().getTime()));
        r.setEmployeeID(Main.EmployeeID);
        return r;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        switch (e.getActionCommand()) {
            case "add":
                if (lblPurchaseOrderID.getText().equals("")) {
                    Message.error("Please choose Purchase Order!");
                    return;
                }
                new Manager().addNew(getValue(), "receipt");
                dispose();
                break;
            case "update":
                new Manager().update(getValue(), "receipt");
                dispose();
                break;
            case "purchase":
                dlgPurchaseOrderList dialog = new dlgPurchaseOrderList(this, true);
                dialog.setVisible(true);
                break;
            case "cancel":
                dispose();
                break;
        }
    }
}
