/*
 * To change this template, choose Tools | Te

 @Override
 public void match() {
 throw new UnsupportedOperationException("Not supported yet.");
 }
 }plates
 * and open the template in the editor.
 */
package gui;

import dao.EmployeeDAO;
import dto.Employee;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * 
 */
public class Main extends javax.swing.JFrame {

    private int x;
    private int y;
    private int clickOnClock = 0;
    LoginDialog ld;

    /**
     * Creates new form Main
     */
    public Main() throws Exception {
        initComponents();
        x = this.getWidth();
        y = this.getHeight();
        motion();
        LoadPane.load(panelComponent, pw);
        new Utility().setIcon("/resources/car.gif", this, null);
        setLang(baseName);
        loadProfile();

        new ThreadTime().start();
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent event) {
                if (!Message.confirm("Are you sure to exit!?")) {
                    return;
                }
                Media m = new Media("Windows XP Shutdown.wav");
                m.start();
                dispose();
                try {
                    m.join();
                } catch (InterruptedException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.exit(0);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXPanel3 = new org.jdesktop.swingx.JXPanel();
        lblCar = new javax.swing.JLabel();
        lblCustomer = new javax.swing.JLabel();
        lblSales = new javax.swing.JLabel();
        lblEmployee = new javax.swing.JLabel();
        jXPanel4 = new org.jdesktop.swingx.JXPanel();
        lblCarReport = new javax.swing.JLabel();
        lblCustomerReport = new javax.swing.JLabel();
        lblEmployeeReport = new javax.swing.JLabel();
        lblManufactoryReport = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbDateTime = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblDeptName = new javax.swing.JLabel();
        txtDeptName = new javax.swing.JTextField();
        lblFullName = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        lblUserID = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnChangePw = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        btnClock = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        pnlPhotoProfile = new javax.swing.JPanel();
        lblPhoto = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        pnlMain = new javax.swing.JPanel();
        jXTaskPaneContainer2 = new org.jdesktop.swingx.JXTaskPaneContainer();
        tspManager = new org.jdesktop.swingx.JXTaskPane();
        tspReport = new org.jdesktop.swingx.JXTaskPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jFile = new javax.swing.JMenu();
        jmiLogout = new javax.swing.JMenuItem();
        jmiExit = new javax.swing.JMenuItem();
        jmOption = new javax.swing.JMenu();
        jMLanguage = new javax.swing.JMenu();
        jmiEnglish = new javax.swing.JMenuItem();
        jmiVietnamese = new javax.swing.JMenuItem();
        jHelp = new javax.swing.JMenu();
        jmiAbout = new javax.swing.JMenuItem();

        jXPanel3.setBackground(new java.awt.Color(214, 223, 247));
        jXPanel3.setLayout(new java.awt.GridLayout(5, 0, 0, 16));

        lblCar.setForeground(new java.awt.Color(0, 0, 153));
        lblCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Taxi.gif"))); // NOI18N
        lblCar.setText("Car");
        lblCar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCarMouseClicked(evt);
            }
        });
        jXPanel3.add(lblCar);

        lblCustomer.setForeground(new java.awt.Color(0, 0, 153));
        lblCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/User group.gif"))); // NOI18N
        lblCustomer.setText("Customer");
        lblCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCustomerMouseClicked(evt);
            }
        });
        jXPanel3.add(lblCustomer);

        lblSales.setForeground(new java.awt.Color(0, 0, 153));
        lblSales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Accounting.gif"))); // NOI18N
        lblSales.setText("Sales");
        lblSales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalesMouseClicked(evt);
            }
        });
        jXPanel3.add(lblSales);

        lblEmployee.setForeground(new java.awt.Color(0, 0, 153));
        lblEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Boss.gif"))); // NOI18N
        lblEmployee.setText("Employee");
        lblEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmployeeMouseClicked(evt);
            }
        });
        jXPanel3.add(lblEmployee);

        jXPanel4.setBackground(new java.awt.Color(214, 223, 247));
        jXPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jXPanel4MouseClicked(evt);
            }
        });
        jXPanel4.setLayout(new java.awt.GridLayout(4, 1, 0, 16));

        lblCarReport.setForeground(new java.awt.Color(0, 0, 153));
        lblCarReport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCarReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Script.gif"))); // NOI18N
        lblCarReport.setText("Car Report");
        lblCarReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCarReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCarReportMouseClicked(evt);
            }
        });
        jXPanel4.add(lblCarReport);

        lblCustomerReport.setForeground(new java.awt.Color(0, 0, 153));
        lblCustomerReport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCustomerReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Script.gif"))); // NOI18N
        lblCustomerReport.setText("Customer Report");
        lblCustomerReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCustomerReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCustomerReportMouseClicked(evt);
            }
        });
        jXPanel4.add(lblCustomerReport);

        lblEmployeeReport.setForeground(new java.awt.Color(0, 0, 153));
        lblEmployeeReport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmployeeReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Script.gif"))); // NOI18N
        lblEmployeeReport.setText("Employee Report");
        lblEmployeeReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEmployeeReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmployeeReportMouseClicked(evt);
            }
        });
        jXPanel4.add(lblEmployeeReport);

        lblManufactoryReport.setForeground(new java.awt.Color(0, 0, 153));
        lblManufactoryReport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblManufactoryReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Script.gif"))); // NOI18N
        lblManufactoryReport.setText("Manufactory Report");
        lblManufactoryReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblManufactoryReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManufactoryReportMouseClicked(evt);
            }
        });
        jXPanel4.add(lblManufactoryReport);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Vehicle Showroom Management System");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lbDateTime.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbDateTime.setForeground(new java.awt.Color(102, 102, 255));
        lbDateTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDateTime.setText("11/22/2022");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lblDeptName.setForeground(new java.awt.Color(51, 51, 51));
        lblDeptName.setText("Dept.Name");

        txtDeptName.setEditable(false);
        txtDeptName.setForeground(new java.awt.Color(255, 51, 0));

        lblFullName.setForeground(new java.awt.Color(51, 51, 51));
        lblFullName.setText("Fullname :");

        txtFullName.setEditable(false);

        lblUserID.setForeground(new java.awt.Color(51, 51, 51));
        lblUserID.setText("UserID :");

        txtUserID.setEditable(false);

        lblPassword.setForeground(new java.awt.Color(51, 51, 51));
        lblPassword.setText("Password :");

        txtPassword.setEditable(false);

        btnChangePw.setForeground(new java.awt.Color(0, 0, 255));
        btnChangePw.setText("Change Profile? Click here...");
        btnChangePw.setContentAreaFilled(false);
        btnChangePw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChangePw.setFocusable(false);
        btnChangePw.setMargin(new java.awt.Insets(2, 0, 2, 0));
        btnChangePw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePwActionPerformed(evt);
            }
        });

        btnRefresh.setForeground(new java.awt.Color(0, 0, 255));
        btnRefresh.setText("Refresh");
        btnRefresh.setContentAreaFilled(false);
        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDeptName)
                            .addComponent(lblFullName)
                            .addComponent(lblUserID)
                            .addComponent(lblPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUserID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFullName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDeptName)
                            .addComponent(txtPassword)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnChangePw, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRefresh)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDeptName, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(lblDeptName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFullName, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(lblFullName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserID, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(lblUserID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(lblPassword))
                .addGap(4, 4, 4)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChangePw)
                .addGap(24, 24, 24))
        );

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        btnClock.setForeground(new java.awt.Color(0, 0, 153));
        btnClock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Clock.gif"))); // NOI18N
        btnClock.setText("Clock");
        btnClock.setToolTipText("Toggle Date/Time");
        btnClock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClock.setFocusable(false);
        btnClock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClock.setMargin(new java.awt.Insets(2, 9, 2, 9));
        btnClock.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClockActionPerformed(evt);
            }
        });
        jToolBar1.add(btnClock);

        btnProfile.setForeground(new java.awt.Color(0, 0, 153));
        btnProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Boss.gif"))); // NOI18N
        btnProfile.setText("My profile");
        btnProfile.setToolTipText("Details/Edit profile");
        btnProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfile.setFocusable(false);
        btnProfile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProfile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });
        jToolBar1.add(btnProfile);

        btnLogout.setForeground(new java.awt.Color(0, 0, 153));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Blue key.gif"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setToolTipText("Logout system");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLogout);

        btnExit.setForeground(new java.awt.Color(0, 0, 153));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Exit.gif"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.setToolTipText("Exit sytem");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExit);

        pnlPhotoProfile.setBackground(new java.awt.Color(255, 255, 255));
        pnlPhotoProfile.setBorder(javax.swing.BorderFactory.createTitledBorder("Photo"));
        pnlPhotoProfile.setLayout(new java.awt.BorderLayout());

        lblPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPhotoProfile.add(lblPhoto, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lbDateTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlPhotoProfile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(pnlPhotoProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(18, 97, 174));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/welcome.gif"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setMaximumSize(new java.awt.Dimension(32767, 32770));
        pnlMain.setLayout(new java.awt.CardLayout());
        pnlMain.add(sales);
        pnlMain.add(employee);
        pnlMain.add(customer);
        pnlMain.add(car);
        pnlMain.add(pw);

        org.jdesktop.swingx.VerticalLayout verticalLayout1 = new org.jdesktop.swingx.VerticalLayout();
        verticalLayout1.setGap(14);
        jXTaskPaneContainer2.setLayout(verticalLayout1);

        tspManager.setCollapsed(true);
        tspManager.setSpecial(true);
        tspManager.setTitle("Manager");
        tspManager.add(this.jXPanel3);
        jXTaskPaneContainer2.add(tspManager);

        tspReport.setCollapsed(true);
        tspReport.setSpecial(true);
        tspReport.setTitle("Report");
        tspReport.add(jXPanel4);
        jXTaskPaneContainer2.add(tspReport);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXTaskPaneContainer2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jXTaskPaneContainer2, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 161, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 466, Short.MAX_VALUE)))
        );

        jFile.setText("File");

        jmiLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logout_16.png"))); // NOI18N
        jmiLogout.setText("Logout");
        jmiLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLogoutActionPerformed(evt);
            }
        });
        jFile.add(jmiLogout);

        jmiExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/exit_16.png"))); // NOI18N
        jmiExit.setText("Exit");
        jmiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExitActionPerformed(evt);
            }
        });
        jFile.add(jmiExit);

        jMenuBar1.add(jFile);

        jmOption.setText("Options");

        jMLanguage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Earth.gif"))); // NOI18N
        jMLanguage.setText("Language");

        jmiEnglish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/england.gif"))); // NOI18N
        jmiEnglish.setText("English");
        jmiEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEnglishActionPerformed(evt);
            }
        });
        jMLanguage.add(jmiEnglish);

        jmiVietnamese.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/vietnam.gif"))); // NOI18N
        jmiVietnamese.setText("Vietnamese");
        jmiVietnamese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVietnameseActionPerformed(evt);
            }
        });
        jMLanguage.add(jmiVietnamese);

        jmOption.add(jMLanguage);

        jMenuBar1.add(jmOption);

        jHelp.setText("Help");

        jmiAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/about_16.png"))); // NOI18N
        jmiAbout.setText("About us");
        jmiAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAboutActionPerformed(evt);
            }
        });
        jHelp.add(jmiAbout);

        jMenuBar1.add(jHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangePwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePwActionPerformed
        // TODO add your handling code here:
        frmEmployee frm = new frmEmployee();
        frm.setTitle("Change Profile");
        frm.loadData(EmployeeID);
        frm.btnAccept.setActionCommand("updateProfile");
        frm.setVisible(true);
    }//GEN-LAST:event_btnChangePwActionPerformed

    private void btnClockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClockActionPerformed
        // TODO add your handling code here:
        clickOnClock++;
    }//GEN-LAST:event_btnClockActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        frmEmployee frm = new frmEmployee();
        frm.setTitle("Profile");
        frm.loadData(EmployeeID);
        frm.btnAccept.setEnabled(false);
        frm.btnBrowse.setEnabled(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        Media m = new Media(new File("Windows XP Exclamation.wav").getAbsolutePath());
        m.start();
        if (Message.confirm("Are you sure to exit!?")) {
            this.dispose();
            m = new Media(new File("Windows XP Shutdown.wav").getAbsolutePath());
            m.start();
            try {
                m.join();
            } catch (InterruptedException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.exit(0);
        }
        return;
    }//GEN-LAST:event_btnExitActionPerformed

    private void lblCarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCarMouseClicked
        // TODO add your handling code here:
        LoadPane.load(panelComponent, car);
    }//GEN-LAST:event_lblCarMouseClicked

    private void lblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerMouseClicked
        // TODO add your handling code here:
        LoadPane.load(panelComponent, customer);
    }//GEN-LAST:event_lblCustomerMouseClicked

    private void lblSalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalesMouseClicked
        // TODO add your handling code here:
        LoadPane.load(panelComponent, sales);
    }//GEN-LAST:event_lblSalesMouseClicked

    private void lblEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmployeeMouseClicked
        // TODO add your handling code here:
        LoadPane.load(panelComponent, employee);
    }//GEN-LAST:event_lblEmployeeMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        if (Message.confirm("Are you sure to logout!?")) {
            new Media(new File("Windows Logoff Sound.wav").getAbsolutePath()).start();
            dispose();
            new LoginDialog(null, false).setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed
    private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExitActionPerformed
        // TODO add your handling code here:
        Media m = new Media(new File("Windows XP Exclamation.wav").getAbsolutePath());
        m.start();
        if (Message.confirm("Are you sure to exit!?")) {
            this.dispose();
            m = new Media(new File("Windows XP Shutdown.wav").getAbsolutePath());
            m.start();
            try {
                m.join();
            } catch (InterruptedException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.exit(0);
        }
        return;
    }//GEN-LAST:event_jmiExitActionPerformed

    private void jmiLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLogoutActionPerformed
        // TODO add your handling code here:
        if (Message.confirm("Are you sure to logout!?")) {
            new Media(new File("Windows Logoff Sound.wav").getAbsolutePath()).start();
            dispose();
            new LoginDialog(null, false).setVisible(true);
        }
    }//GEN-LAST:event_jmiLogoutActionPerformed

    private void jmiAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAboutActionPerformed
        // TODO add your handling code here:
        new AboutUs(this, true);
    }//GEN-LAST:event_jmiAboutActionPerformed

    private void jXPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXPanel4MouseClicked
        // TODO add your handling code here:
        new AboutUs(this, true);
    }//GEN-LAST:event_jXPanel4MouseClicked

    private void lblCarReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCarReportMouseClicked
        // TODO add your handling code here:
        new Utility().getReport("Car");
    }//GEN-LAST:event_lblCarReportMouseClicked

    private void lblCustomerReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerReportMouseClicked
        // TODO add your handling code here:
        new Utility().getReport("Customer");
    }//GEN-LAST:event_lblCustomerReportMouseClicked

    private void lblEmployeeReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmployeeReportMouseClicked
        // TODO add your handling code here:
        new Utility().getReport("Employee");
    }//GEN-LAST:event_lblEmployeeReportMouseClicked

    private void lblManufactoryReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManufactoryReportMouseClicked
        // TODO add your handling code here:
        new Utility().getReport("Manufactory");
    }//GEN-LAST:event_lblManufactoryReportMouseClicked

    private void jmiEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEnglishActionPerformed
        // TODO add your handling code here:
        baseName = "MyResources_en_US";
        setLang(baseName);
    }//GEN-LAST:event_jmiEnglishActionPerformed

    private void jmiVietnameseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVietnameseActionPerformed
        // TODO add your handling code here:
        baseName = "MyResources_vi_VN";
        setLang(baseName);
    }//GEN-LAST:event_jmiVietnameseActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
     // TODO add your handling code here:
     LoadPane.load(panelComponent, pw);
     new Utility().setIcon("/resources/car.gif", this, null);
        setLang(baseName);
        loadProfile();
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePw;
    private javax.swing.JButton btnClock;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JMenu jFile;
    private javax.swing.JMenu jHelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMLanguage;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JToolBar jToolBar1;
    private org.jdesktop.swingx.JXPanel jXPanel3;
    private org.jdesktop.swingx.JXPanel jXPanel4;
    private org.jdesktop.swingx.JXTaskPaneContainer jXTaskPaneContainer2;
    private javax.swing.JMenu jmOption;
    private javax.swing.JMenuItem jmiAbout;
    private javax.swing.JMenuItem jmiEnglish;
    private javax.swing.JMenuItem jmiExit;
    private javax.swing.JMenuItem jmiLogout;
    private javax.swing.JMenuItem jmiVietnamese;
    private javax.swing.JLabel lbDateTime;
    private javax.swing.JLabel lblCar;
    private javax.swing.JLabel lblCarReport;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblCustomerReport;
    private javax.swing.JLabel lblDeptName;
    private javax.swing.JLabel lblEmployee;
    private javax.swing.JLabel lblEmployeeReport;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblManufactoryReport;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblSales;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlPhotoProfile;
    private org.jdesktop.swingx.JXTaskPane tspManager;
    private org.jdesktop.swingx.JXTaskPane tspReport;
    private javax.swing.JTextField txtDeptName;
    public static javax.swing.JTextField txtFullName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserID;
    // End of variables declaration//GEN-END:variables
    public static long EmployeeID;
    public static String DepartmentName, baseName = "MyResources_en_US";
    pnlSales sales = new pnlSales();
    pnlEmployee employee = new pnlEmployee();
    pnlCar car = new pnlCar();
    pnlCustomer customer = new pnlCustomer();
    pnlWelcome pw = new pnlWelcome();
    JPanel[] panelComponent = {sales, employee, car, customer, pw};

    public void setLang(String baseName) {
        Locale locale = Locale.getDefault();
        ResourceBundle rb = ResourceBundle.getBundle(baseName, locale);
        jmOption.setText(rb.getString("option"));
        jmiLogout.setText(rb.getString("logout"));
        jMLanguage.setText(rb.getString("language"));
        jmiEnglish.setText(rb.getString("eng"));
        jmiVietnamese.setText(rb.getString("vie"));
        jmiExit.setText(rb.getString("exit"));
        jFile.setText(rb.getString("file"));
        jHelp.setText(rb.getString("help"));
        btnClock.setText(rb.getString("clock"));
        btnProfile.setText(rb.getString("myProfile"));
        btnLogout.setText(rb.getString("logout"));
        pnlPhotoProfile.setBorder(javax.swing.BorderFactory.createTitledBorder(rb.getString("photo")));
        lblDeptName.setText(rb.getString("deptName"));
        lblFullName.setText(rb.getString("fullName"));
        lblUserID.setText(rb.getString("userID"));
        btnChangePw.setText(rb.getString("changeProfile"));
        tspManager.setTitle(rb.getString("manager"));
        tspReport.setTitle(rb.getString("report"));
        jmiAbout.setText(rb.getString("about"));
        lblCar.setText(rb.getString("car"));
        lblCustomer.setText(rb.getString("customer"));
        lblEmployee.setText(rb.getString("employee"));
        lblCarReport.setText(rb.getString("carReport"));
        lblEmployeeReport.setText(rb.getString("employeeReport"));
        lblManufactoryReport.setText(rb.getString("manufactoryReport"));
        lblSales.setText(rb.getString("sales"));
        car.lblSearchCar.setText(rb.getString("searchCar"));
        JTableHeader th = car.tblCar.getTableHeader();
        TableColumnModel tcm = th.getColumnModel();
        TableColumn tc = tcm.getColumn(0);
        tc.setHeaderValue(rb.getString("carNo"));
        tc = tcm.getColumn(1);
        tc.setHeaderValue(rb.getString("modelName"));
        tc = tcm.getColumn(2);
        tc.setHeaderValue(rb.getString("name"));
        tc = tcm.getColumn(3);
        tc.setHeaderValue(rb.getString("price"));
        th.repaint();
        car.tbpCar.setTitleAt(0, rb.getString("car"));
        car.tbpCar.setTitleAt(1, rb.getString("models"));
        car.btnNewCar.setText(rb.getString("new"));
        car.btnUpdateCar.setText(rb.getString("update"));
        car.btnDeleteCar.setText(rb.getString("delete"));
        car.btnDetailsCar.setText(rb.getString("details"));
        car.btnReportCar.setText(rb.getString("report"));
        car.btnUpdateListCar.setText(rb.getString("updateList"));
        car.lblSearchModel.setText(rb.getString("searchModel"));
        th = car.tblModels.getTableHeader();
        tcm = th.getColumnModel();
        tc = tcm.getColumn(0);
        tc.setHeaderValue(rb.getString("modelName"));
        tc = tcm.getColumn(1);
        tc.setHeaderValue(rb.getString("manufactoryName"));
        th.repaint();
        car.btnNewModel.setText(rb.getString("new"));
        car.btnUpdateModel.setText(rb.getString("update"));
        car.btnDeleteModel.setText(rb.getString("delete"));
        car.btnDetailsModel.setText(rb.getString("details"));
        car.btnUpdateListModels.setText(rb.getString("updateList"));
        car.tbpCar.setTitleAt(2, rb.getString("services"));
        car.lblNameService.setText(rb.getString("name"));
        car.lblDescriptService.setText(rb.getString("descript"));
        car.btnNewService.setText(rb.getString("new"));
        car.btnUpdateService.setText(rb.getString("update"));
        car.btnDeleteService.setText(rb.getString("delete"));
        car.pnlServiceInfor.setBorder(javax.swing.BorderFactory.createTitledBorder(rb.getString("serviceInfor")));
        th = car.tblServices.getTableHeader();
        tcm = th.getColumnModel();
        tc = tcm.getColumn(0);
        tc.setHeaderValue(rb.getString("ID"));
        tc = tcm.getColumn(1);
        tc.setHeaderValue(rb.getString("name"));
        tc = tcm.getColumn(2);
        tc.setHeaderValue(rb.getString("descript"));
        th.repaint();
        car.tbpCar.setTitleAt(3, rb.getString("purchaseOrder"));
        car.pickOrder.setText(rb.getString("pick"));
        car.cbxShowPurchase.setText(rb.getString("showAll"));
        car.btnReportPurchase.setText(rb.getString("report"));
        car.btnUpdateListPurchase.setText(rb.getString("updateList"));
        car.btnNewPurchase.setText(rb.getString("new"));
        car.btnUpdatePurchase.setText(rb.getString("update"));
        car.btnDeletePurchase.setText(rb.getString("delete"));
        car.btnDetailsPurchase.setText(rb.getString("details"));
        th = car.tblOrder.getTableHeader();
        tcm = th.getColumnModel();
        tc = tcm.getColumn(0);
        tc.setHeaderValue(rb.getString("ID"));
        tc = tcm.getColumn(1);
        tc.setHeaderValue(rb.getString("empName"));
        tc = tcm.getColumn(2);
        tc.setHeaderValue(rb.getString("date"));
        th.repaint();
        car.tbpCar.setTitleAt(4, rb.getString("receipt"));
        car.pickReceipt.setText(rb.getString("pick"));
        car.cbxShowReceipt.setText(rb.getString("showAll"));
        car.btnNewReceipt.setText(rb.getString("new"));
        car.btnUpdateReceipt.setText(rb.getString("update"));
        car.btnDeleteReceipt.setText(rb.getString("delete"));
        car.btnDetailsReceipt.setText("details");
        car.btnUpdateListReceipt.setText("updateList");
        th = car.tblReceipt.getTableHeader();
        tcm = th.getColumnModel();
        tc = tcm.getColumn(0);
        tc.setHeaderValue(rb.getString("ID"));
        tc = tcm.getColumn(1);
        tc.setHeaderValue(rb.getString("purchaseID"));
        tc = tcm.getColumn(2);
        tc.setHeaderValue(rb.getString("empName"));
        tc = tcm.getColumn(3);
        tc.setHeaderValue(rb.getString("date"));
        th.repaint();
        car.tbpCar.setTitleAt(5, rb.getString("manufactory"));
        car.lblSearchManufactory.setText(rb.getString("searchManu"));
        car.btnNewManufactory.setText(rb.getString("new"));
        car.btnUpdateManufactory.setText(rb.getString("update"));
        car.btnDeleteManufactory.setText(rb.getString("delete"));
        car.btnDetailsManufactory.setText(rb.getString("details"));
        car.btnManufactoryReport.setText(rb.getString("report"));
        car.btnUpdateListManufactory.setText(rb.getString("updateList"));
        th = car.tblManufactory.getTableHeader();
        tcm = th.getColumnModel();
        tc = tcm.getColumn(0);
        tc.setHeaderValue(rb.getString("ID"));
        tc = tcm.getColumn(1);
        tc.setHeaderValue(rb.getString("name"));
        tc = tcm.getColumn(2);
        tc.setHeaderValue(rb.getString("address"));
        tc = tcm.getColumn(3);
        tc.setHeaderValue(rb.getString("phone"));
        th.repaint();
        customer.tbpCustomer.setTitleAt(0, rb.getString("customer"));
        customer.lblSearchCustomer.setText(rb.getString("searchCust"));
        customer.btnCustomerReport.setText(rb.getString("report"));
        customer.btnNewCustomer.setText(rb.getString("new"));
        customer.btnUpdateCustomer.setText(rb.getString("update"));
        customer.btnDeleteCustomer.setText(rb.getString("delete"));
        customer.btnDetailsCustomer.setText(rb.getString("details"));
        th = customer.tblCustomer.getTableHeader();
        tcm = th.getColumnModel();
        tc = tcm.getColumn(0);
        tc.setHeaderValue(rb.getString("custID"));
        tc = tcm.getColumn(1);
        tc.setHeaderValue(rb.getString("firstName"));
        tc = tcm.getColumn(2);
        tc.setHeaderValue(rb.getString("lastName"));
        tc = tcm.getColumn(3);
        tc.setHeaderValue(rb.getString("sex"));
        tc = tcm.getColumn(4);
        tc.setHeaderValue(rb.getString("dateOfBirth"));
        th.repaint();
        sales.tbpSales.setTitleAt(0, rb.getString("order"));
        sales.tbpSales.setTitleAt(1, rb.getString("assigning"));
        sales.tsWeekly.setTitle(rb.getString("salary"));
        sales.lblPickOrder.setText(rb.getString("pick"));
        sales.lblPickAssigning.setText(rb.getString("pick"));
        sales.lblShowOrder.setText(rb.getString("showAll"));
        sales.lblShowAssigning.setText(rb.getString("showAll"));
        sales.btnNewOrder.setText(rb.getString("new"));
        sales.btnUpdateOrder.setText(rb.getString("update"));
        sales.btnDeleteOrder.setText(rb.getString("delete"));
        sales.btnDetailsOrder.setText(rb.getString("details"));
        sales.btnUpdateListOrder.setText(rb.getString("updateList"));
        sales.btnUpdateListAssigning.setText(rb.getString("updateList"));
        sales.btnReportOrder.setText(rb.getString("report"));
        sales.btnNewAssigning.setText(rb.getString("new"));
        sales.btnUpdateAssigning.setText(rb.getString("update"));
        sales.btnDeleteAssigning.setText("delete");
        sales.btnDetailsAssigning.setText(rb.getString("details"));
        th = sales.tblOrder.getTableHeader();
        tcm = th.getColumnModel();
        tc = tcm.getColumn(0);
        tc.setHeaderValue(rb.getString("orderID"));
        tc = tcm.getColumn(1);
        tc.setHeaderValue(rb.getString("custName"));
        tc = tcm.getColumn(2);
        tc.setHeaderValue(rb.getString("onOrder"));
        tc = tcm.getColumn(3);
        tc.setHeaderValue(rb.getString("confirmation"));
        tc = tcm.getColumn(4);
        tc.setHeaderValue(rb.getString("empName"));
        th.repaint();
        th = sales.tblAssigning.getTableHeader();
        tcm = th.getColumnModel();
        tc = tcm.getColumn(0);
        tc.setHeaderValue(rb.getString("assigningID"));
        tc = tcm.getColumn(1);
        tc.setHeaderValue(rb.getString("orderID"));
        tc = tcm.getColumn(2);
        tc.setHeaderValue(rb.getString("onAssigning"));
        tc = tcm.getColumn(3);
        tc.setHeaderValue(rb.getString("custName"));
        tc = tcm.getColumn(4);
        tc.setHeaderValue(rb.getString("empName"));
        th.repaint();
        employee.tbpEmployee.removeAll();
        employee.tbpEmployee.addTab(rb.getString("employee"), employee.pnlEmp);
        if (Main.DepartmentName.equals("HR")) {
            employee.tbpEmployee.addTab(rb.getString("department"), employee.department);
        }
//        employee.tbpEmployee.setTitleAt(0, rb.getString("employee"));
//        employee.tbpEmployee.setTitleAt(1, rb.getString("department"));
        employee.lblSearchEmployee.setText(rb.getString("searchEmp"));
        employee.btnNewEmp.setText(rb.getString("new"));
        employee.btnUpdateEmp.setText(rb.getString("update"));
        employee.btnDeleteEmp.setText(rb.getString("delete"));
        employee.btnDetailsEmp.setText(rb.getString("details"));
        employee.btnUpdateListEmployee.setText(rb.getString("updateList"));
        employee.btnEmployeeReport.setText(rb.getString("report"));
        th = employee.tblEmployee.getTableHeader();
        tcm = th.getColumnModel();
        tc = tcm.getColumn(0);
        tc.setHeaderValue(rb.getString("empID"));
        tc = tcm.getColumn(1);
        tc.setHeaderValue(rb.getString("deptName"));
        tc = tcm.getColumn(2);
        tc.setHeaderValue(rb.getString("firstName"));
        tc = tcm.getColumn(3);
        tc.setHeaderValue(rb.getString("lastName"));
        tc = tcm.getColumn(4);
        tc.setHeaderValue(rb.getString("sex"));
        tc = tcm.getColumn(5);
        tc.setHeaderValue(rb.getString("dateOfBirth"));
        th.repaint();
        employee.pnlDept.setBorder(javax.swing.BorderFactory.createTitledBorder(rb.getString("department")));
        employee.lblName.setText(rb.getString("name"));
        employee.btnNewDept.setText(rb.getString("new"));
        employee.btnDeleteDept.setText(rb.getString("delete"));
        th = employee.tblDepartment.getTableHeader();
        tcm = th.getColumnModel();
        tc = tcm.getColumn(0);
        tc.setHeaderValue(rb.getString("deptName"));
        lblCustomerReport.setText(rb.getString("customerReport"));
    }

    public void loadProfile() {
        Employee emp = new EmployeeDAO().getEmployee(EmployeeID);
        lblPhoto.setIcon(new ImageIcon(emp.getPhoto()));
        txtDeptName.setText(emp.getDepartmentName());
        txtFullName.setText(emp.getFirstName() + " " + emp.getLastName());
        txtUserID.setText(emp.getUserName());
        txtPassword.setText(emp.getPassword());
    }

    private void motion() {
        this.setSize(0, 0);
        new Thread(new SizeMonitor(this, x, y)).start();
        new Media(new File("Windows XP Startup.wav").getAbsolutePath()).start();
    }

    public class ThreadTime extends Thread {

        @Override
        public void run() {
            SimpleDateFormat dayFormat = new SimpleDateFormat("EEE, MMM d, yyyy",Locale.CANADA);
            SimpleDateFormat hourFormat = new SimpleDateFormat("HH:mm:ss");
            while (true) {
                Date d = new Date();
                if (clickOnClock % 2 == 0) {
                    lbDateTime.setText(dayFormat.format(d));
                } else {
                    lbDateTime.setText(hourFormat.format(d));
                }
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    System.out.println(e.getMessage());
                }
            }
        }
    }
}
