/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bll.Manager;
import dao.CustomerDAO;
import dto.Customer;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.decorator.ColorHighlighter;
import org.jdesktop.swingx.decorator.HighlightPredicate;
import org.jdesktop.swingx.decorator.Highlighter;
import org.jdesktop.swingx.decorator.HighlighterFactory;

/**
 *
 * 
 */
public class pnlCustomer extends javax.swing.JPanel implements ActionListener {

    /**
     * Creates new form pnlCar
     */
    public pnlCustomer() {
        initComponents();
        loadCustomerData("");
        JButton[] arrButton = {btnNewCustomer, btnUpdateCustomer, btnDeleteCustomer, btnDetailsCustomer, btnUpdateListCustomer};
        if (!Main.DepartmentName.equals("Sales")) {
            new Utility().disableButton(arrButton);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbpCustomer = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new org.jdesktop.swingx.JXTable();
        txtSearchCustomer = new org.jdesktop.swingx.JXSearchField();
        jPanel7 = new javax.swing.JPanel();
        btnNewCustomer = new javax.swing.JButton();
        btnUpdateCustomer = new javax.swing.JButton();
        btnDeleteCustomer = new javax.swing.JButton();
        btnDetailsCustomer = new javax.swing.JButton();
        lblSearchCustomer = new javax.swing.JLabel();
        btnUpdateListCustomer = new javax.swing.JButton();
        btnCustomerReport = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Highlighter simpleStripHL = HighlighterFactory.createSimpleStriping();
        tblCustomer.addHighlighter(new ColorHighlighter(HighlightPredicate.ROLLOVER_ROW,
            null, new Color(0, 0, 255)));
    tblCustomer.setHighlighters(simpleStripHL);
    tblCustomer.addHighlighter(new ColorHighlighter(HighlightPredicate.ROLLOVER_ROW,
        null, new Color(255, 102, 0)));
tblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        tblCustomerMouseClicked(evt);
    }
    });
    jScrollPane1.setViewportView(tblCustomer);

    jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 680, 270));

    txtSearchCustomer.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            txtSearchCustomerKeyReleased(evt);
        }
    });
    jPanel3.add(txtSearchCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 72, 210, 20));

    jPanel7.setLayout(new java.awt.GridLayout(1, 0));

    btnNewCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
    btnNewCustomer.setText("New");
    btnNewCustomer.setActionCommand("newCustomer");
    btnNewCustomer.addActionListener(this);
    jPanel7.add(btnNewCustomer);

    btnUpdateCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/update.png"))); // NOI18N
    btnUpdateCustomer.setText("Update");
    btnUpdateCustomer.setEnabled(false);
    btnUpdateCustomer.setActionCommand("updateCustomer");
    btnUpdateCustomer.addActionListener(this);
    jPanel7.add(btnUpdateCustomer);

    btnDeleteCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/delete.png"))); // NOI18N
    btnDeleteCustomer.setText("Delete");
    btnDeleteCustomer.setEnabled(false);
    btnDeleteCustomer.setActionCommand("deleteCustomer");
    btnDeleteCustomer.addActionListener(this);
    jPanel7.add(btnDeleteCustomer);

    btnDetailsCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/about_16.png"))); // NOI18N
    btnDetailsCustomer.setText("Details");
    btnDetailsCustomer.setActionCommand("detailsCustomer");
    btnDetailsCustomer.addActionListener(this);
    btnDetailsCustomer.setEnabled(false);
    jPanel7.add(btnDetailsCustomer);

    jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 400, 30));

    lblSearchCustomer.setForeground(new java.awt.Color(51, 51, 51));
    lblSearchCustomer.setText("Search Customer's Name");
    jPanel3.add(lblSearchCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 44, -1, 30));

    btnUpdateListCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/update.png"))); // NOI18N
    btnUpdateListCustomer.setText("Update List");
    btnUpdateListCustomer.setActionCommand("updateList");
    btnUpdateListCustomer.addActionListener(this);
    jPanel3.add(btnUpdateListCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 110, 30));

    btnCustomerReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Script20x20.gif"))); // NOI18N
    btnCustomerReport.setText("Report");
    btnCustomerReport.setActionCommand("reportCustomer");
    btnCustomerReport.addActionListener(this);
    jPanel3.add(btnCustomerReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

    tbpCustomer.addTab("Customer", jPanel3);

    add(tbpCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void tblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerMouseClicked
        // TODO add your handling code here:
        row = tblCustomer.getSelectedRow();
        if (row >= 0) {
            CustomerID = (long) tblCustomer.getValueAt(row, 0);
            btnUpdateCustomer.setEnabled(true);
            btnDeleteCustomer.setEnabled(true);
            btnDetailsCustomer.setEnabled(true);
        }

    }//GEN-LAST:event_tblCustomerMouseClicked

    private void txtSearchCustomerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchCustomerKeyReleased
        // TODO add your handling code here:
        if (!txtSearchCustomer.getText().equals("")) {
            loadCustomerData("search");
        } else {
            loadCustomerData("");
        }
        btnUpdateCustomer.setEnabled(false);
        btnDeleteCustomer.setEnabled(false);
        btnDetailsCustomer.setEnabled(false);
    }//GEN-LAST:event_txtSearchCustomerKeyReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCustomerReport;
    public javax.swing.JButton btnDeleteCustomer;
    public javax.swing.JButton btnDetailsCustomer;
    public javax.swing.JButton btnNewCustomer;
    public javax.swing.JButton btnUpdateCustomer;
    public javax.swing.JButton btnUpdateListCustomer;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblSearchCustomer;
    public org.jdesktop.swingx.JXTable tblCustomer;
    public javax.swing.JTabbedPane tbpCustomer;
    public org.jdesktop.swingx.JXSearchField txtSearchCustomer;
    // End of variables declaration//GEN-END:variables
    int row = 0;
    frmCustomer frmCus;
    long CustomerID;

    public void loadCustomerData(String type) {
         Locale locale = Locale.getDefault();
        ResourceBundle rb = ResourceBundle.getBundle(Main.baseName, locale);
        ArrayList list;
        String keyword = txtSearchCustomer.getText();
        if (type.equals("search") && !keyword.equals("")) {
            list = new CustomerDAO().getList(keyword);
        } else {
            list = new Manager().getList("customer");
        }
        Vector vData = new Vector();
        Vector vColumn = new Vector();
        vColumn.removeAllElements();
        vColumn.add(rb.getString("custID"));
        vColumn.add(rb.getString("firstName"));
        vColumn.add(rb.getString("lastName"));
        vColumn.add(rb.getString("sex"));
        vColumn.add(rb.getString("dateOfBirth"));
        for (int i = 0; i < list.size(); i++) {
            Vector vRow = new Vector();
            Customer c = (Customer) list.get(i);
            vRow.add(c.getCustomerID());
            vRow.add(c.getFirstName());
            vRow.add(c.getLastName());
            String st;
            if (c.isSex()) {
                st = rb.getString("male");
            } else {
                st = rb.getString("female");
            }
            vRow.add(st);
            Date d = c.getDateOfBirth();
            d.setDate(d.getDate());
            SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            vRow.add(df.format(d));
            vData.add(vRow);
        }
        DefaultTableModel model = new DefaultTableModel(vData, vColumn);
        tblCustomer.setModel(model);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        switch (e.getActionCommand()) {
            case "newCustomer":
                if (frmCus == null) {
                    frmCus = new frmCustomer();
                } else {
                    frmCus.requestFocus();
                }
                frmCus.setTitle("Add New Customer");
                frmCus.btnAccept.setActionCommand("add");
                frmCus.btnAccept.setEnabled(true);
                frmCus.loadEmptyForm();
                frmCus.setVisible(true);
                break;
            case "updateCustomer":
                btnUpdateCustomer.setEnabled(false);
                btnDeleteCustomer.setEnabled(false);
                btnDetailsCustomer.setEnabled(false);
                if (frmCus == null) {
                    frmCus = new frmCustomer();
                } else {
                    frmCus.requestFocus();
                }
                frmCus.setTitle("Update Customer Information");
                frmCus.btnAccept.setActionCommand("update");
                frmCus.btnAccept.setEnabled(true);
                frmCus.setValues(CustomerID);
                frmCus.setVisible(true);
                break;
            case "deleteCustomer":
                new Manager().delete(CustomerID, "customer");
                btnUpdateCustomer.setEnabled(false);
                btnDeleteCustomer.setEnabled(false);
                btnDetailsCustomer.setEnabled(false);
                break;
            case "detailsCustomer":
                btnUpdateCustomer.setEnabled(false);
                btnDeleteCustomer.setEnabled(false);
                btnDetailsCustomer.setEnabled(false);
                if (frmCus == null) {
                    frmCus = new frmCustomer();
                } else {
                    frmCus.requestFocus();
                }
                frmCus.setTitle("Details Customer Information");
                frmCus.btnAccept.setEnabled(false);
                frmCus.setValues(CustomerID);
                frmCus.setVisible(true);
                break;
            case "updateList":
                new Media(new File("chimes.wav").getAbsolutePath()).start();
                btnUpdateCustomer.setEnabled(false);
                btnDeleteCustomer.setEnabled(false);
                btnDetailsCustomer.setEnabled(false);
                loadCustomerData("");
                break;
            case "reportCustomer":
                new Utility().getReport("Customer");
                break;
        }
    }
}
